sudo: required

language: node_js
node_js:
  - 8

notifications:
  email: false

before_script:
  - npm install
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git config user.name
  - git config user.email

script:
  - ./node_modules/\@angular/cli/bin/ng build --prod --base-href "/auras-photo-app/"
  - ./node_modules/angular-cli-ghpages/bin/angular-cli-ghpages --repo=https://GHTOKEN@github.com/thiagohersan/auras-photo-app.git --no-silent
